version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  data: {}

networks:
  default:
    name: postgres_network

