version: '3'

services:
  postgres-db:
    image: "postgres"
    container_name: "postgres_container"
    #volumes:
    # - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=crypto_tracker_db
    ports:
      - 5432:5432

  crypto-tracker-app:
    container_name: "app_container"
    build: .
    ports:
      - "8084:80"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/crypto_tracker_db
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


